//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuratProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        public int id { get; set; }
        public string Toplanti_Konusu { get; set; }
        public string Başlama_Saati { get; set; }
        public string Bitiş_Saati { get; set; }
        public string Katılımcılar { get; set; }
    }
}
